# Chapter 3 Numbers, Dates, and Times

Performing mathematical calculations with integers and floating-point numbers is easy in Python. However, if you need to perform calculations with fractions, arrays, or dates and times, a bit more work is required. The focus of this chapter is on such topics.

## 3.1 Rounding Numberical Values

For simple rounding, use the built-in round(value, ndigits) function.

In [9]:
print(round(1.23, 1))

print(round(1.27, 1))

print(round(-1.27, 1))

print(round(1.25361, 3))

a = 1627731
print(round(a, -1))
print(round(a, -2))
print(round(a, -3))

x = 1.23456
print(format(x, '0.2f'))
print(format(x, '0.3f'))
print('value is {:0.3f}'.format(x))

a = 2.1
b = 4.2 
c = a + b 
print(c)
print(round(c, 2))

1.2
1.3
-1.3
1.254
1627730
1627700
1628000
1.23
1.235
value is 1.235
6.300000000000001
6.3


## 3.2 Performing Accurate Decimal Calculations

A well-known issue with floating-point numbers is that they can’t accurately represent all base-10 decimals. Moreover, even simple mathematical calculations introduce small errors.

In [17]:
from decimal import Decimal

a = Decimal('4.2')
b = Decimal('2.1')

a + b
print(a + b)
(a + b) == Decimal('6.3')

6.3


True

In [19]:
from decimal import localcontext

a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)

with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.7647058823529411764705882353
0.765


In [20]:
nums = [1.23e+18, 1, -1.23e+18]
sum(nums)

0.0

## 3.3 Formatting Numbers for Output

To format a single number for output, use the built-in format() function.

In [29]:
x = 1234.56789

# Two decimal places of accuracy
print(format(x, '0.2f'))
# Right justified in 10 chars, one-digit accuracy
print(format(x, '>10.1f'))

# Left justified
print(format(x, '<10.1f'))

# Centered
print(format(x, '^10.1f'))

# Inclusion of thousands separator
print(format(x, ','))

print(format(x, '0,.1f'))

print(format(x, 'e'))

print(format(x, '0.2E'))

print('The value is {:0,.2f}'.format(x))

1234.57
    1234.6
1234.6    
  1234.6  
1,234.56789
1,234.6
1.234568e+03
1.23E+03
The value is 1,234.57


## 3.4 Working with Binary, Octal, and Hexadecimal Integers

To convert an integer into a binary, octal, or hexadecimal text string, use the **bin()**, **oct()**, or **hex()** functions, 

In [33]:
x = 1234

print(bin(x))
print(format(x, 'b'))

print(oct(x))
print(format(x, 'o'))

print(hex(x))
print(format(x, 'x'))

0b10011010010
10011010010
0o2322
2322
0x4d2
4d2


In [ ]:
## 3.5 Packing and Unpacking Large Integers from 

In [37]:
data =b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

print(len(data))

print(int.from_bytes(data, 'little'))

print(int.from_bytes(data, 'big'))

x = 94522842520747284487117727783387188

print(x.to_bytes(16, 'big'))

print(x.to_bytes(16, 'little'))

16
69120565665751139577663547927094891008
94522842520747284487117727783387188
b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'


## 3.6 Performing Complex-Valued Math

Complex numbers can be specified using the **complex(real, imag)** function or by floating-point numbers with a j suffix.

In [43]:
a = complex(2, 4)
b = 3 - 5j
print(a)
print(b)

print(a.real)
print(a.imag)
print(a.conjugate())
print(a + b)
print(a * b)
print(a / b)
print(abs(a))

(2+4j)
(3-5j)
2.0
4.0
(2-4j)
(5-1j)
(26+2j)
(-0.4117647058823529+0.6470588235294118j)
4.47213595499958


In [49]:
import numpy as np
a = np.array([2 + 3j, 4 + 5j, 6 - 7j, 8 +9j])
print(a)

print(a + 2)
print(np.sin(a))

import cmath
cmath.sqrt(-1)

[2.+3.j 4.+5.j 6.-7.j 8.+9.j]
[ 4.+3.j  6.+5.j  8.-7.j 10.+9.j]
[   9.15449915  -4.16890696j  -56.16227422 -48.50245524j
 -153.20827755-526.47684926j 4008.42651446-589.49948373j]


1j

## 3.7 Working with Infinity and NaNs

Python has no special syntax to represent these special floating-point values, but they can be created using **float()**. 

In [62]:
a = float('inf')
b = float('-inf')
c = float('nan')
import math
print(math.isinf(a))
print(math.isnan(c))

a = float('inf')
print( a + 45)

print( a * 10)

print(10 / a)

a = float('inf')
print(a/a)

b = float('-inf')
print(a + b)

c = float('nan')
print(c + 23)
print(c / 2)
print(c * 2)
print(math.sqrt(c))

c = float('nan')
d = float('nan')
print(c == d)
print( c is d)

# Because of this, the only safe way to test for a NaN value is to use math.isnan(), as shown in this recipe.

True
True
inf
inf
0.0
nan
nan
nan
nan
nan
nan
False
False


## 3.8 Calculating with Fractions

The fractions module can be used to perform mathematical calculations involving fractions.


In [67]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print( a + b )
print( a * b )

# Getting numerator/denominator
c = a * b 
print(c.numerator)
print(c.denominator)

# Converting to a float
print(float(c))

# Limiting the denominator of a value
print(c.limit_denominator(8))

# Converting a float to a fraction
x = 3.75
y = Fraction(*x.as_integer_ratio())
print(y)

27/16
35/64
35
64
0.546875
4/7
15/4


## 3.9 Calculating with Large Numerical Arrays

For any heavy computation involving arrays, use the **NumPy library**. The major feature of NumPy is that it gives Python an array object that is much more efficient and better suited for mathematical calculation than a standard Python list.

In [13]:
# Numpy arrays
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
print(ax * 2)
print(ax + 10)
print(ax + ay)
print(ax * ay)
print(np.sqrt(ax))
print(np.cos(ax))

grid = np.zeros(shape=(10000,10000), dtype=float)
print(grid)

grid +=10
print(grid)
np.sin(grid)

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
# Select row 1 
print(a[1])
# Select column 1
print(a[:,1])
# Select a subregion and change it
print(a[1:3, 1:3])
a[1:3, 1:3] += 10
print(a)

# Broadcast a row vector across an operation on all rows
print(a + [100, 101, 102, 103])
print(a)

# Conditional assignment on an array
print(np.where(a < 10, a , 10))

[2 4 6 8]
[11 12 13 14]
[ 6  8 10 12]
[ 5 12 21 32]
[1.         1.41421356 1.73205081 2.        ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 ...
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 2  6 10]
[[ 6  7]
 [10 11]]
[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]
[[101 103 105 107]
 [105 117 119 111]
 [109 121 123 115]]
[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]
[[ 1  2  3  4]
 [ 5 10 10  8]
 [ 9 10 10 10]]


## 3.10 Performing Matrix and Linear Algebra Calculations

The NumPy library has a **matrix** object that can be used for this purpose.


In [20]:
import numpy as np
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
print(m)

# Return trasnpose
print(m.T)

# Return inverse
print(m.I)

# Create a vector and multiply
v = np.matrix([[2],[3],[4]])
print(v)
print(m * v)

[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
[[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]
[[2]
 [3]
 [4]]
[[ 8]
 [32]
 [ 2]]


In [26]:
import numpy.linalg

# Determinate
print(numpy.linalg.det(m))

# Eigenvalues
print(numpy.linalg.eigvals(m))

# Solve for x in mx = v
x = numpy.linalg.solve(m, v)
print(x)

print(m * x)
print(v)

-229.99999999999983
[-13.11474312   2.75956154   6.35518158]
[[0.96521739]
 [0.17391304]
 [0.46086957]]
[[2.]
 [3.]
 [4.]]
[[2]
 [3]
 [4]]


In [ ]:
## 3.11 Picking Things at Random

The random module has various functions for random numbers and picking random items.

In [37]:
import random
values = [1, 2, 3, 4, 5, 6]
print(random.choice(values))
print(random.choice(values))
print(random.choice(values))
print(random.choice(values))
print(random.choice(values))

print(random.sample(values, 2))
print(random.sample(values, 2))
print(random.sample(values, 3))
print(random.sample(values, 3))

random.shuffle(values)
print(values)
random.shuffle(values)
print(values)

print(random.randint(0,10))
print(random.randint(0,10))
print(random.randint(0,10))
print(random.randint(0,10))
print(random.randint(0,10))
print(random.randint(0,10))

# To produce uniform floating-point values in the range 0 to 1, use random.random()
print(random.random())
print(random.random())
print(random.random())

print(random.getrandbits(200))


5
4
2
1
3
[5, 6]
[3, 6]
[5, 4, 2]
[2, 6, 1]
[4, 3, 2, 1, 6, 5]
[2, 4, 1, 3, 6, 5]
7
7
6
10
4
7
0.5092692559251516
0.9772591864107453
0.06905536647130184
40193541444406098870654615659440132759375199588479869950971
None
None


## 3.12  Converting Days to Seconds, and Other Basic Time Conversions

To perform conversions and arithmetic involving different units of time, use the **datetime** module.

In [48]:
from datetime import timedelta
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b
print(c.days)
print(c.seconds)
print(c.seconds/3600)
print(c.total_seconds()/3600)

from datetime import datetime
a = datetime(2012, 9, 23)
print(a + timedelta(days=10))

b = datetime(2012, 12, 21)
d = b - a
print(d.days)

now = datetime.today()
print(now)

print(now + timedelta(minutes=10))
a = datetime(2012, 3, 1)
b = datetime(2012, 2, 28)
print(a - b)
print((a - b).days)

c = datetime(2013, 3, 1)
d = datetime(2013, 2, 28)
print((c - d).days)

2
37800
10.5
58.5
2012-10-03 00:00:00
89
2021-01-27 16:48:50.229070
2021-01-27 16:58:50.229070
2 days, 0:00:00
2
1


In [57]:
from dateutil.relativedelta import relativedelta
a = datetime(2012, 9, 23)
print( a + relativedelta(months=+1))
print( a + relativedelta(months=+4))

# Time between two dates
b = datetime(2012, 12, 21)
d = b - a
print(d)

d = relativedelta(b, a)
print(d)
print(d.months)
print(d.days)

2012-10-23 00:00:00
2013-01-23 00:00:00
89 days, 0:00:00
relativedelta(months=+2, days=+28)
2
28


In [ ]:
## 3.13 Determining Last Friday's Date

Python’s **datetime** module has utility functions and classes to help perform calculations like this.

In [62]:
from datetime import datetime, timedelta

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                'Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date=None): 
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname) 
    days_ago = (7 + day_num - day_num_target) % 7 
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago) 
    return target_date

print(datetime.today()) # For reference

print(get_previous_byday('Monday'))
print(get_previous_byday('Tuesday')) # Previous week, not today
print(get_previous_byday('Friday'))
print(get_previous_byday('Sunday', datetime(2012, 12, 21)))

2021-01-27 17:07:42.620856
2021-01-25 17:07:42.621137
2021-01-26 17:07:42.621216
2021-01-22 17:07:42.621280
2012-12-16 00:00:00


In [64]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import * 
d = datetime.now()
print(d)

# Next Friday
print(d + relativedelta(weekday=FR))

# Last Friday
print(d + relativedelta(weekday=FR(-1)))

2021-01-27 17:13:11.619938
2021-01-29 17:13:11.619938
2021-01-22 17:13:11.619938


## 3.14 Finding the Date Range for the Current Month


In [5]:
from datetime import datetime, timedelta
def date_range(start, stop, step): 
    while start < stop:
        yield start 
        start += step

for d in date_range(datetime(2012,9,1), datetime(2012,10,1), timedelta(hours=6)):
    print(d)

2012-09-01 00:00:00
2012-09-01 06:00:00
2012-09-01 12:00:00
2012-09-01 18:00:00
2012-09-02 00:00:00
2012-09-02 06:00:00
2012-09-02 12:00:00
2012-09-02 18:00:00
2012-09-03 00:00:00
2012-09-03 06:00:00
2012-09-03 12:00:00
2012-09-03 18:00:00
2012-09-04 00:00:00
2012-09-04 06:00:00
2012-09-04 12:00:00
2012-09-04 18:00:00
2012-09-05 00:00:00
2012-09-05 06:00:00
2012-09-05 12:00:00
2012-09-05 18:00:00
2012-09-06 00:00:00
2012-09-06 06:00:00
2012-09-06 12:00:00
2012-09-06 18:00:00
2012-09-07 00:00:00
2012-09-07 06:00:00
2012-09-07 12:00:00
2012-09-07 18:00:00
2012-09-08 00:00:00
2012-09-08 06:00:00
2012-09-08 12:00:00
2012-09-08 18:00:00
2012-09-09 00:00:00
2012-09-09 06:00:00
2012-09-09 12:00:00
2012-09-09 18:00:00
2012-09-10 00:00:00
2012-09-10 06:00:00
2012-09-10 12:00:00
2012-09-10 18:00:00
2012-09-11 00:00:00
2012-09-11 06:00:00
2012-09-11 12:00:00
2012-09-11 18:00:00
2012-09-12 00:00:00
2012-09-12 06:00:00
2012-09-12 12:00:00
2012-09-12 18:00:00
2012-09-13 00:00:00
2012-09-13 06:00:00


## 3.15 Converting Strings into Datetimes

Python’s standard **datetime** module is typically the easy solution for this.

In [9]:
from datetime import datetime
text = '2012-09-20'
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime.now()
diff = z - y
print(diff)
print(z)
nice_z = datetime.strftime(z, '%A %B %d, %Y')
print(nice_z)

3051 days, 19:33:12.959411
2021-01-27 19:33:12.959411
Wednesday January 27, 2021


## 3.16 Manipulating Dates Involving Time Zones

For almost any problem involving time zones, you should use the pytz module. This package provides the Olson time zone database, which is the de facto standard for time zone information found in many languages and operating systems.

In [24]:
from datetime import datetime
from pytz import timezone

d = datetime(2012, 12, 21, 9, 30, 0)
print(d)

# Localize the date for Chicago
central = timezone('US/Central')
loc_d = central.localize(d)
print("US/Central:" + str(loc_d))

# Convert to Bangalore time
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print("Asia/Kolkata:" + str(bang_d))

2012-12-21 09:30:00
US/Central:2012-12-21 09:30:00-06:00
Asia/Kolkata:2012-12-21 21:00:00+05:30


In [35]:
d = datetime(2013, 3, 10, 1, 45)
loc_d = central.localize(d)
print(loc_d)

from datetime import timedelta
later = central.normalize(loc_d + timedelta(minutes=30))
print(later)

import pytz

utc_d = loc_d.astimezone(pytz.utc)
print(utc_d)

later_utc = utc_d + timedelta(minutes=30)
print(later_utc.astimezone(central))
print(pytz.country_timezones['IN'])

2013-03-10 01:45:00-06:00
2013-03-10 03:15:00-05:00
2013-03-10 07:45:00+00:00
2013-03-10 03:15:00-05:00
['Asia/Kolkata']
